# Generated by Django 3.2.9 on 2021-11-21 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster_path', models.CharField(max_length=200)),
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('adult', models.BooleanField()),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
                ('movie_keywords', models.ManyToManyField(related_name='keyword_movies', to='movies.Keyword')),
                ('movie_like_users', models.ManyToManyField(related_name='user_like_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
