<template>
  <div class="fade-in-right">
    <!-- <vs-card type="2" @click="goMovieDetail" style="padding: 10px;"> -->
    <vs-card type="2" style="padding: 10px;">
      <template #title>
        <h3>{{ movie.title }}</h3>
      </template>
      <template #img>
        <img :src="getPoster()" alt="poster" @click="goMovieDetail">
      </template>
      <template #text>
        <p @click="goMovieDetail">
          {{ movie.overview | setOverview }}
        </p>
      </template>
      <template #interactions>
        <vs-button v-if="showingLike" icon style="background-color: white;" @click="movieLike">
          <i class="fas fa-heart" style="color: red;"></i>
        </vs-button>        
        <vs-button v-else icon style="background-color: white;" @click="movieLike">
          <i class="far fa-heart" style="color: red;"></i>
        </vs-button>
        <vs-button class="btn-chat" shadow primary>
          <i class='bx bx-chat' ></i>
          <span class="span">
            {{ movie.like_count }}
          </span>
        </vs-button>
      </template>
    </vs-card>
  </div>
</template>

<script>
import Vue from 'vue'
import Vuesax from 'vuesax'
import 'vuesax/dist/vuesax.css'
import axios from 'axios'


Vue.use(Vuesax, {

})

import { mapState } from 'vuex'
export default {
  name: 'MovieListItem',
  props: {
    movie: Object
  },
  data: function () {
    return {
      showingLike: false
    }
  },
  methods: {
    getPoster: function () {
      return `https://image.tmdb.org/t/p/w185/${this.movie.poster_path}`
    },
    goMovieDetail: function () {
      this.$router.push({ name: 'MovieDetail', params: {movie_pk: this.movie.id}})
    },
    movieLike: function () {
      axios({
        method: 'post',
        url: `${this.tmpUrl}/movies/movie/${this.movie.id}/like/`,
        headers: this.header
      })
      .then(() => {
        this.showingLike = !this.showingLike
        this.$store.dispatch('getMovies')
      })
      .catch(err => {
        console.log(err)
      })
    }
  },
  filters: {
    setOverview: function (data) {
      return data.substring(0, 30) + '...'
    }
  },
  created: function () {
    for (const user of this.movie.movie_like_users) {
      if (user.username === this.loginUser) {
        this.showingLike = true
      }
    }
  },
  computed: {
    ...mapState([
      'tmpUrl',
      'header',
      'loginUser',
    ]),
  }
}
</script>

<style>
/* ----------------------------------------------
 * Generated by Animista on 2021-11-24 22:15:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-right
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-right {
  0% {
    -webkit-transform: translateX(50px);
            transform: translateX(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes fade-in-right {
  0% {
    -webkit-transform: translateX(50px);
            transform: translateX(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}


  .card {
    width: 220px;
    height: 330px;
    padding: 0 10px;
  }

  .card-image {
    width: 220px;
    height: 300px;
  }
  .fade-in-right {
    -webkit-animation: fade-in-right 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
            animation: fade-in-right 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  }
</style>